# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Food-Able' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SDWebImageSwiftUI'
  pod 'SwiftyJSON'
  pod 'Alamofire'

  # Pods for Food-Able

end
